### ISSUE TITLE
No tests found

### ISSUE THREAD

**Issue by Phonesis** [mpinardi/cucumber-performance#3]
Hello, I am very keen to use this package and have followed your readme instructions to set it all up with a feature file.

However, no matter what I try the runner simply doesn't seem to do anything. Not tests are being found:

Total Ran: 0
RunTime: PT0.109S

I have this set in a runner file:

public class RunPerformanceTests { 
        public static void main(String[] args)
        { 
	        PerfRuntimeOptions options = new PerfRuntimeOptions();
		options.addTagFilters(Arrays.asList(new String[]{"not @bskip","@PerformanceTest"}));
		options.addPlanPaths(Arrays.asList(new String[]{"src/test/java/graphql/testing/features"}));
		options.addCucumberOptions(Arrays.asList(new String[]{"-g","features","src/test/java/graphql/testing/features"}));
		CucumberPerf cukePerf = new CucumberPerf(options);
		System.out.println("Total Ran: "+cukePerf.getTotalRanCount());
		System.out.println("RunTime: "+cukePerf.getRunTime());
		System.exit(0);        
        }
}

The paths are correct. 

I am using cucumber version 3.0.2. Is this supported or do you suggest a different version?

**Comment by mpinardi-bao** [comment]
Hi, 
**Updated**
The current cucumber version for cucumber-perf 1.2.0 is cucumber 3.0.2
It seems your Plan path is pointing to your features directory.
options.addPlanPaths(Arrays.asList(new String[]{"src/test/java/graphql/testing/features"}));
Are there any .plan files in this directory. Otherwise it has nothing to run.
